library('xlsx')
trial=createWorkbook()
crime= read.csv("C:\\Users\\monis\\Desktop\\R programming\\R\\Data Sets\\crime.csv",stringsAsFactors = FALSE)
crimex=createSheet(wb=mdf, sheetName="CRIMEX")
df_new=createSheet(wb=mdf, sheetName="RANDOM")
addDataFrame(x = crimex, sheet = CRIMEX)
addDataFrame(x = df_new, sheet = RANDOM)
readr::write_excel_csv(crime, path = "C:\\Users\\monis\\Desktop\\R programming\\R\\Data Sets\\ExcelinR2.xlsx", col_names = FALSE)
saveWorkbook(trial, file = "C:\\Users\\monis\\Desktop\\R programming\\R\\Data Sets\\Trial_final.xlsx")
title_style <- CellStyle(mdf) + Font(wb, heightInPoints = 16,color = "blue", isBold = TRUE,underline = 1)
subtitle_style <- CellStyle(wb) + Font(wb, heightInPoints = 14, isItalic = TRUE, isBold = FALSE)

library(readr)
write.csv(crime, file="C:\\Users\\monis\\Desktop\\R programming\\R\\Data Sets\\ExcelinR5.csv")
